In [3]:
# Lap trinh Giao dich tu dong voi Binance   
# Buoc 1: Khai bao thu muc  
import sys
sys.path.append('../Common/')   
import CommonBinance

# Buoc 2: Goi code den CommonBinance    
from datetime import datetime, timedelta
import schedule
import time
import random
symbol = 'ETH/USDT' 
from_date = (datetime.now() - timedelta(days=100)).strftime('%Y-%m-%d')  # Lay 100 ngay truoc   
to_date = (datetime.now() + timedelta(days=1)).strftime('%Y-%m-%d') 
timeframe = '1d' # 1d   
data = CommonBinance.CommonBinance.loaddataBinance_FromTo(symbol, from_date, to_date, timeframe)    
    
# Buoc 3: Hien thi du lieu  
data
#     #

      Datetime     Open     High      Low    Close        Volume
0   2024-11-02  2511.49  2523.45  2470.00  2494.23  1.459611e+05
1   2024-11-03  2494.23  2496.39  2411.00  2457.73  2.760091e+05
2   2024-11-04  2457.73  2491.39  2357.59  2398.21  3.063170e+05
3   2024-11-05  2398.21  2480.00  2380.74  2422.55  3.316193e+05
4   2024-11-06  2422.60  2744.70  2420.30  2721.87  1.002141e+06
..         ...      ...      ...      ...      ...           ...
96  2025-02-06  2788.25  2857.64  2655.28  2686.64  7.194600e+05
97  2025-02-07  2686.63  2797.50  2562.51  2622.10  6.954674e+05
98  2025-02-08  2622.11  2667.30  2588.80  2632.46  3.796852e+05
99  2025-02-09  2632.46  2698.90  2520.02  2627.18  3.871668e+05
100 2025-02-10  2627.18  2660.00  2559.85  2632.87  1.573373e+05

[101 rows x 6 columns]